http:
  routers:
    routerAuthentik:
      entryPoints:
        - "web-http"
      service: authentik
      rule: Host(`auth.saw.rwth-aachen.de`)
      middlewares:
       - redirect-to-https

    routerAuthentikSecure:
      entryPoints:
        - "web-http-secure"
      service: authentik
      rule: Host(`auth.saw.rwth-aachen.de`)
      tls: {}
      middlewares:
        - only-allow-nag

  services:
    authentik:
      loadBalancer:
        servers:
          - url: http://10.10.12.109/
