http:
  routers:
    routerPaperless:
      entryPoints:
        - "web-http"
      service: paperless
      rule: Host(`paperless.saw.rwth-aachen.de`)
      middlewares:
       - redirect-to-https

    routerPaperlessSecure:
      entryPoints:
        - "web-http-secure"
      service: paperless
      rule: Host(`paperless.saw.rwth-aachen.de`)
      tls: {}
      middlewares:
        - only-allow-saw

  services:
    paperless:
      loadBalancer:
        servers:
          - url: http://10.10.12.107:8000/
