http:
  routers:
    routerPublicSite:
      entryPoints:
        - "web-http"
      service: public-site
      rule: Host(`www.saw.rwth-aachen.de`) || Host(`saw.rwth-aachen.de`)
      middlewares:
       - redirect-to-https

    routerPublicSiteSecure:
      entryPoints:
        - "web-http-secure"
      service: public-site
      rule: Host(`www.saw.rwth-aachen.de`) || Host(`saw.rwth-aachen.de`)
      tls: {}

  services:
    public-site:
      loadBalancer:
        servers:
          - url: http://site-public:80/