global:
  sendAnonymousUsage: false
entryPoints:
  web-http-secure:
    address: ":443"
  web-http:
    address: ":80"
providers:
  file:
    directory: /etc/traefik/dynamic
    watch: false
log:
  level: WARN
accessLog: {}
