server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    # Hides server information (e.g. nginx version) in responses
    server_tokens off;

    # Access Logs are handled by traefik; Client IP is always docker internal network 
    access_log off;

    # Disallow files.publii.json
    location ~ /files.publii.json {
        deny all;
        return 404;
    }

    # Include /email/saw-mail-rz-ev.txt from external folder
    location ~ /email/saw-mail-rz-ev.txt {
        # This should only be accessable by the RWTH Mailserver, but we do not see the IP Address here!
        # Maybe I should actually use Traefik like a reverse proxy, you know, its intended purpose?
        alias /email/saw-mail-rz-ev.txt;
    }

    # Serve all files
    location / {
        root   /usr/share/nginx/html;
        index  index.html;
    }

    error_page  404  /404.html;
}
